debug: false
uuid: 414564e2-2ffc-4d25-8bed-8aaef8d17339
token_id: d4C0oxhKB5i8Eqn2
token: XuawuS2BYKiEEv8kshybdmZjd0sIX2DQcMmBJQ8hnrUpcjuC0qQPHxISxeezQItc
api:
  host: 0.0.0.0
  port: 80
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/b262-20-161-77-250.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/b262-20-161-77-250.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://b262-20-161-77-250.ngrok-free.app'
